import './globals.css';
import type { Metadata } from 'next';
import Sidebar from './sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <Sidebar />
        <main className="flex min-h-screen w-screen flex-col items-center justify-between p-24
      max-lg:block"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
